apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deephealth-backend.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "deephealth-backend.name" . }}
    helm.sh/chart: {{ include "deephealth-backend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "deephealth-backend.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "deephealth-backend.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
        - name: {{ .Chart.Name }}-init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh","-c"]
          args: ["wait-for-it.sh -h {{ include "deephealth-backend.fullname" . }}-postgresql -p {{ .Values.postgresql.service.port }} && init.sh"]
          env:
            - name: DJANGO_ENV
              value: "/app/config"
            - name: ADMIN_USER
              value: "{{ .Values.backend.admin.username }}"
            - name: ADMIN_PASSWORD
              value: "{{ .Values.backend.admin.password }}"
            - name: ADMIN_EMAIL
              value: "{{ .Values.backend.admin.email }}"
          volumeMounts:
            - name: backend-secrets
              mountPath: "/app/config"
              subPath: config
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash","-c"]
          args: ["python manage.py runserver 0.0.0.0:{{ .Values.backend.service.containerPort }}"]
          env:
            - name: DJANGO_ENV
              value: "/app/config"
          volumeMounts:
            - name: backend-secrets
              mountPath: "/app/config"
              subPath: config
          ports:
            - name: backend-port
              containerPort: {{ .Values.backend.service.containerPort }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
      volumes:
        - name: backend-secrets
          secret:
            secretName: backend-secrets
            defaultMode: 0644
    {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
