apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deephealth-backend.fullname" . }}-celery
  labels:
    app.kubernetes.io/name: {{ include "deephealth-backend.name" . }}
    helm.sh/chart: {{ include "deephealth-backend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "deephealth-backend.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "deephealth-backend.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-celery-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh","-c"]
          args: ["wait-for-it.sh -h {{ .Release.Name }}-rabbitmq -p {{ .Values.broker.service.port }} && python manage.py celery"]
          env:
            - name: DJANGO_ENV
              value: "/app/.env/config"
          volumeMounts:
            - name: backend-secrets
              mountPath: "/app/.env"
          ports:
            - name: celery-port
              containerPort: {{ .Values.celery.service.containerPort }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.celery.resources | nindent 12 }}
      volumes:
        - name: backend-secrets
          secret:
            secretName: backend-secrets
            defaultMode: 0644
    {{- with .Values.celery.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.celery.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.celery.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
