{{- if .Values.console.enabled  }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deephealth-backend.fullname" . }}-console
  labels:
    app.kubernetes.io/name: {{ include "deephealth-backend.name" . }}-console
    app.kubernetes.io/part-of: {{ include "deephealth-backend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/component: debug-console
    helm.sh/chart: {{ include "deephealth-backend.chart" . }}
spec:
  replicas: {{ .Values.console.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "deephealth-backend.name" . }}-console
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "deephealth-backend.name" . }}-console
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: console
          image: {{ .Values.console.image.repository }}:{{ .Values.console.image.tag }}
          imagePullPolicy: {{ .Values.console.image.pullPolicy }}
          command: ["sleep","infinity"]
          env:
{{ include "deephealth-backend.common-env" . | indent 12 }}
          volumeMounts:
{{ include "deephealth-backend.common-mount-paths" . | indent 12 }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
      volumes:
        - name: nginx-static-files
          persistentVolumeClaim:
            claimName: {{ tpl .Values.nginx.serverDataVolumeClaim . }}
            readOnly: false
{{ include "deephealth-backend.common-volumes" . | indent 8 }}
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}