{{- if .Values.console.enabled  }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deephealth-backend.fullname" . }}-console
  labels:
    app.kubernetes.io/name: {{ include "deephealth-backend.name" . }}-console
    helm.sh/chart: {{ include "deephealth-backend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.console.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "deephealth-backend.name" . }}-console
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "deephealth-backend.name" . }}-console
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.console.image.repository }}
          imagePullPolicy: {{ .Values.console.image.pullPolicy }}
          command: ["sleep","infinity"]
          env:
{{ include "deephealth-backend.common-env" . | indent 12 }}
          volumeMounts:
            - name: backend-secrets
              mountPath: "/app/.env"
              subPath: config
            - name: nginx-static-files
              mountPath: "/app/static"
            - name: datasets-volume
              mountPath: {{ .Values.dataPaths.datasets }}
            - name: training-volume
              mountPath: {{ .Values.dataPaths.training }}
            - name: inference-volume
              mountPath: {{ .Values.dataPaths.inference }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
      volumes:
        - name: backend-secrets
          secret:
            secretName: {{ include "deephealth-backend.fullname" . }}-backend-secrets
            defaultMode: 0644
        - name: nginx-static-files
          persistentVolumeClaim:
            claimName: {{ include "deephealth-backend.fullname" . }}-nginx-{{ .Values.nginx.serverDataVolumeClaim }}
            readOnly: false
        - name: datasets-volume
          persistentVolumeClaim:
            claimName: {{ include "deephealth-backend.fullname" . }}-datasets
            readOnly: false
        - name: training-volume
          persistentVolumeClaim:
            claimName: {{ include "deephealth-backend.fullname" . }}-training
            readOnly: false
        - name: inference-volume
          persistentVolumeClaim:
            claimName: {{ include "deephealth-backend.fullname" . }}-inference
            readOnly: false
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}