apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "deephealth-backend.fullname" . }}-init
  labels:
    app.kubernetes.io/name: {{ include "deephealth-backend.name" . }}-init
    helm.sh/chart: {{ include "deephealth-backend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
    app.kubernetes.io/name: {{ include "deephealth-backend.name" . }}-init
    app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
    labels:
      app.kubernetes.io/name: {{ include "deephealth-backend.name" . }}-init
      app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
        - name: wait-for-postgresql
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          command: 
            - /bin/sh
            - -c
            - until PGPASSWORD=${POSTGRES_PASSWORD} psql -h "{{ include "deephealth-backend.fullname" . }}-postgresql" -U "{{ .Values.postgresql.postgresqlUsername }}" {{ .Values.postgresql.postgresqlDatabase }} -c '\q'; do 
                >&2 echo "PostgreSQL is unavailable -- sleep 2 seconds and retry" ;
                sleep 2 ;
              done ;
              echo "PostgreSQL ready"
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "deephealth-backend.fullname" . }}-postgresql
                  key: postgresql-password
          volumeMounts:
            - name: backend-secrets
              mountPath: "/app/config"
              subPath: config
      containers:
      - name: django-init
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        command: ["/bin/sh","-c"]
        args: ["init.sh"]
        env:
{{ include "deephealth-backend.adminCredentials" . | indent 10 }}
{{ include "deephealth-backend.common-env" . | indent 10 }}
        volumeMounts:
          - name: backend-secrets
            mountPath: "/app/config"
            subPath: config
      - name: django-static
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        command: ["python","manage.py","collectstatic","--noinput"]
        env:
{{ include "deephealth-backend.adminCredentials" . | indent 10 }}
{{ include "deephealth-backend.common-env" . | indent 10 }}
        volumeMounts:
          - name: backend-secrets
            mountPath: "/app/config"
            subPath: config
          - name: nginx-static-files
            mountPath: "/app/static"
      restartPolicy: Never
      volumes:
      - name: backend-secrets
        secret:
          secretName: {{ include "deephealth-backend.fullname" . }}-secrets
          defaultMode: 0644
      - name: nginx-static-files
        persistentVolumeClaim:
          claimName: {{ include "deephealth-backend.fullname" . }}-nginx-{{ .Values.nginx.serverDataVolumeClaim }}
          readOnly: false
    {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  backoffLimit: 4