
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "deephealth-backend.fullname" . }}-nginx-proxy-config
  labels:
    app.kubernetes.io/name: {{ include "deephealth-backend.name" . }}-nginx
    app.kubernetes.io/part-of: {{ include "deephealth-backend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/component: proxy-configmap
    helm.sh/chart: {{ include "deephealth-backend.chart" . }}
data:
  backend.conf: |-
    # set upstream server
    upstream backend_app {
      # fail_timeout=0 means we always retry an upstream even if it failed
      # to return a good HTTP response
      server {{ include "deephealth-backend.fullname" . }}-backend:{{ .Values.backend.service.port }} fail_timeout=0;
    }

    server {
      listen 8000;

      client_max_body_size 4G;

      # set the correct host(s) for your site
      server_name localhost;

      keepalive_timeout 60;

      # set localtion for static files
      location {{ include "deephealth-backend.static_files.url" . }} {
        alias {{ include "deephealth-backend.static_files.path" . }};
      }

      # set proxy location
      location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        # we don't want nginx trying to do something clever with
        # redirects, we set the Host: header above already.
        proxy_redirect off;
        proxy_pass http://backend_app;
      }
    }