apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "deephealth-backend.fullname" . }}-datasets
  labels:
    app.kubernetes.io/name: {{ include "deephealth-backend.name" . }}-datasets
    helm.sh/chart: {{ include "deephealth-backend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: {{ .Values.global.datasetsStorageSize }}
    storageClassName: {{ .Values.global.datasetsStorageClass }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "deephealth-backend.fullname" . }}-training
  labels:
    app.kubernetes.io/name: {{ include "deephealth-backend.name" . }}-training
    helm.sh/chart: {{ include "deephealth-backend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: {{ .Values.global.trainingStorageSize }}
    storageClassName: {{ .Values.global.trainingStorageClass }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "deephealth-backend.fullname" . }}-inference
  labels:
    app.kubernetes.io/name: {{ include "deephealth-backend.name" . }}-inference
    helm.sh/chart: {{ include "deephealth-backend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: {{ .Values.global.inferenceStorageSize }}
    storageClassName: {{ .Values.global.inferenceStorageClass }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "deephealth-backend.fullname" . }}-nginx-{{ .Values.nginx.serverDataVolumeClaim }}
  labels:
    app.kubernetes.io/name: {{ include "deephealth-backend.name" . }}-{{ .Values.nginx.serverDataVolumeClaim }}
    helm.sh/chart: {{ include "deephealth-backend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: {{ .Values.nginx.staticFilesVolumeSize }}
    storageClassName: {{ .Values.nginx.staticFilesStorageClass }}
