{{- if not .Values.backend.persistence.data.existingClaim -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-{{ include "deephealth-backend.fullname" . }}-backend
  labels:
    app.kubernetes.io/name: {{ include "deephealth-backend.name" . }}
    app.kubernetes.io/part-of: {{ include "deephealth-backend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/component: backend-datasets
    helm.sh/chart: {{ include "deephealth-backend.chart" . }}
  annotations:
    helm.sh/chart: {{ include "deephealth-backend.chart" . }}
    helm.sh/resource-policy: keep
spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: {{ .Values.backend.persistence.data.size }}
    storageClassName: {{ .Values.backend.persistence.data.storageClass }}
---
{{- end -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ tpl .Values.nginx.serverDataVolumeClaim . }}
  labels:
    app.kubernetes.io/name: {{ include "deephealth-backend.name" . }}
    app.kubernetes.io/part-of: {{ include "deephealth-backend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/component: api-backend
    helm.sh/chart: {{ include "deephealth-backend.chart" . }}
  annotations:
    helm.sh/chart: {{ include "deephealth-backend.chart" . }}
spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: {{ .Values.backend.persistence.staticFiles.size }}
    storageClassName: {{ .Values.backend.persistence.staticFiles.storageClass }}
