{{- if not .Values.backend.persistence.datasets.existingClaim -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "deephealth-backend.fullname" . }}-datasets
  labels:
    app.kubernetes.io/name: {{ include "deephealth-backend.name" . }}-datasets
    helm.sh/chart: {{ include "deephealth-backend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: {{ .Values.backend.persistence.datasets.size }}
    storageClassName: {{ .Values.backend.persistence.datasets.storageClass }}
---
{{- end -}}
{{- if not .Values.backend.persistence.training.existingClaim -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "deephealth-backend.fullname" . }}-training
  labels:
    app.kubernetes.io/name: {{ include "deephealth-backend.name" . }}-training
    helm.sh/chart: {{ include "deephealth-backend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: {{ .Values.backend.persistence.training.size }}
    storageClassName: {{ .Values.backend.persistence.training.storageClass }}
---
{{- end -}}
{{- if not .Values.backend.persistence.inference.existingClaim -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "deephealth-backend.fullname" . }}-inference
  labels:
    app.kubernetes.io/name: {{ include "deephealth-backend.name" . }}-inference
    helm.sh/chart: {{ include "deephealth-backend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: {{ .Values.backend.persistence.inference.size }}
    storageClassName: {{ .Values.backend.persistence.inference.storageClass }}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "deephealth-backend.fullname" . }}-nginx-{{ .Values.nginx.serverDataVolumeClaim }}
  labels:
    app.kubernetes.io/name: {{ include "deephealth-backend.name" . }}-{{ .Values.nginx.serverDataVolumeClaim }}
    helm.sh/chart: {{ include "deephealth-backend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: {{ .Values.backend.persistence.staticFiles.size }}
    storageClassName: {{ .Values.backend.persistence.staticFiles.storageClass }}
