kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "deephealth-backend.name" . }}-role
  labels:
      app.kubernetes.io/name: {{ include "deephealth-backend.name" . }}-role
      helm.sh/chart: {{ include "deephealth-backend.chart" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups: ["", "extensions", "apps", "batch"]
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ include "deephealth-backend.name" . }}-rbac
  labels:
    app.kubernetes.io/name: {{ include "deephealth-backend.name" . }}-rbac
    helm.sh/chart: {{ include "deephealth-backend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: {{ include "deephealth-backend.name" . }}-role
  apiGroup: rbac.authorization.k8s.io