apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deephealth-backend.fullname" . }}-backend-secrets
  labels:
    app.kubernetes.io/name: {{ include "deephealth-backend.name" . }}
    helm.sh/chart: {{ include "deephealth-backend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  config: |-
    # Allow DEBUG mode. Don't run with debug turned on in production!
    DEBUG={{ .Values.global.debug }}

    # Set SECRET_KEY. Keep the secret key used in production secret!
    SECRET_KEY={{ .Values.djangoSecret }}

    # List of allowed hosts
    ALLOWED_HOSTS="localhost,127.0.0.1,{{ include "deephealth-backend.fullname" . }}{{- range .Values.ingress.hosts }},{{ .host }}{{- end }}"
    
    # Database connection settings
    #DATABASE_URL=sqlite:///my-local-sqlite.db # SQLite DB
    DATABASE_URL=psql://{{ .Values.postgresql.postgresqlUsername }}:{{ .Values.postgresql.postgresqlPassword }}@{{ include "deephealth-backend.fullname" . }}-postgresql:{{ .Values.postgresql.service.port }}/{{ .Values.postgresql.postgresqlDatabase }}

    # Relative path for static resources
    STATIC_URL={{ .Values.global.staticUrl }}

    # Data directories
    TRAINING_DIR={{ .Values.dataPaths.training }}
    INFERENCE_DIR={{ .Values.dataPaths.inference }}
    DATASETS_DIR={{ .Values.dataPaths.datasets }}

    # RabbitMQ Credentials
    # see https://hub.docker.com/_/rabbitmq
    RABBITMQ_BROKER_URL=amqp://{{ .Values.broker.rabbitmq.username }}:{{ .Values.broker.rabbitmq.password }}@{{ include "deephealth-backend.fullname" . }}-rabbitmq:{{ .Values.broker.service.port }}
