apiVersion: v1
kind: Service
metadata:
  name: {{ include "deephealth-backend.fullname" . }}-backend
  labels:
    app.kubernetes.io/name: {{ include "deephealth-backend.name" . }}-backend
    app.kubernetes.io/part-of: {{ include "deephealth-backend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/component: api-backend-service
    helm.sh/chart: {{ include "deephealth-backend.chart" . }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.containerPort }}
      protocol: TCP
      name: backend-port
  selector:
    app.kubernetes.io/name: {{ include "deephealth-backend.name" . }}-backend
    app.kubernetes.io/instance: {{ .Release.Name }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "deephealth-backend.fullname" . }}-endpoint
  labels:
    app.kubernetes.io/name: {{ include "deephealth-backend.name" . }}-endpoint
    app.kubernetes.io/part-of: {{ include "deephealth-backend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/component: api-backend-endpoint-service
    helm.sh/chart: {{ include "deephealth-backend.chart" . }}
spec:
  type: {{ .Values.endpoint.service.type }}
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: {{ .Release.Name }}
